### ISSUE TITLE
PR messages should be extended, not overwritten

### ISSUE THREAD

**Issue by jonathanloske** [adevinta/maiao#37]
The PR message depends on the contents of the first commit but for various reasons, it is beneficial to use GitHub's included PR message editor instead:

* Serving pictures
* Editing the message after-the fact (very annoying to do locally)
* Getting a live preview of the content of the message
* Staying compatible with commit-linting rules

Therefore, it would be nice if `git review` could enhance the PR message instead of overwriting it.

**Current behavior**
Every time `git review` is run, the PR message gets overwritten

**Desired behavior**
When `git review` is run, only the content that `git review` autocreates gets overwritten.

**Comment by joaoqalves** [comment]
Hi Jonathan!

> The PR message depends on the contents of the first commit but for various reasons, it is beneficial to use GitHub's included PR message editor instead:
>+ Serving pictures
>+ Editing the message after-the fact (very annoying to do locally)
>+ Getting a live preview of the content of the message
>+ Staying compatible with commit-linting rules

I understand some of the pain points. I want to go over them one by one.

# Serving pictures

This is a valid pain point. What we've done so far is to add these images to the first comment of a PR. Not sure if this is good enough for you.

# Editing message after-the-fact

Why is it _annoying_ to do it locally? Usually, my flow is to do a `git commit --amend` or `git rebase -i` so I edit the messages I want. Then force-push. 

As part of Maiao's philosophy, keeping commit messages and PRs in sync has value. Commit messages are part of git, but PRs are not. Hence, it's easy to do a `git blame` or to check context locally, even when Github is down or if we move to another source code repository anytime.

# Getting a live preview of the content of the message

This is very dependent on the setup each person uses. I use VS code and it [supports](https://code.visualstudio.com/Docs/languages/markdown#_editor-and-preview-synchronization) markdown preview. Wouldn't that suffice for you?

# Staying compatible with commit-linting rules

Do you care to share more about these rules? And why would a PR message violate them?

**Comment by jonathanloske** [comment]
This all makes sense and I am happy with the explanations, closing now :)
