### ISSUE TITLE
Missing release

### ISSUE THREAD

**Issue by Ligio** [adevinta/maiao#8]
Hi!
I see the latest tag [here](https://github.com/adevinta/maiao/tags) was released on 10 Dec 2021 but the latest PR merged into the master branch was from 19 Dec 2021.

Maybe it's worth releasing a 1.0.1?

Thanks!

**Comment by tjamet** [comment]
I just released [1.0.1](https://github.com/adevinta/maiao/releases/tag/1.0.1) you should be able to download and run successfully.
Let me know if you face any difficulties
